# k8s/rabbitmq/secret.yaml
  apiVersion: v1
  kind: Secret
  metadata:
    name: rabbitmq-secret
    namespace: migration-orchestrator
  type: Opaque
  stringData:
    #Username and password is for application clients (workers,API) to connect to RabbitMQ
    #The erlang cookie is an internal authentication. This cookie needs to match for the nodes to talk to each other.
    #Since only one node is being deployed the erlang cookie won't break config, but for future scaling this is best practice
    username: admin
    password: changeme
    erlang-cookie: a-long-random-secret-string-here