"""create_state_transition_history_table

Revision ID: 016a2b89eb21
Revises: 1c3b2f69d458
Create Date: 2026-02-25 14:11:53.951152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision: str = '016a2b89eb21'
down_revision: Union[str, Sequence[str], None] = '1c3b2f69d458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "state_transition_history",

        # --- Identity ---
        # UUID generated by PostgreSQL itself via gen_random_uuid().
        # Using a DB-generated UUID rather than an application-generated one
        # means the ID is assigned atomically with the INSERT — no risk of the
        # application generating an ID that never reaches the database.
        sa.Column(
            "transition_id",
            sa.String(),
            server_default=sa.text("gen_random_uuid()::text"),
            nullable=False,
        ),

        # Foreign key to servers — you cannot insert a history record for a
        # server_id that does not exist in the servers table. Referential
        # integrity enforced at the database level, not just the application.
        sa.Column("server_id", sa.String(), nullable=False),

        # --- Transition ---
        sa.Column("from_state", sa.String(), nullable=False),
        sa.Column("to_state", sa.String(), nullable=False),

        # --- Cause ---
        # job_id and job_type trace this transition back to the exact RabbitMQ
        # message that caused it. Null only for manual transitions (approval gates
        # resolved by a human directly through the API).
        sa.Column("job_id", sa.String(), nullable=True),
        sa.Column("job_type", sa.String(), nullable=True),

        # triggered_by is either 'system' (automated job) or an engineer's ID
        # (manual intervention via the API or an approval gate decision).
        sa.Column("triggered_by", sa.String(), nullable=False),

        # --- Timestamp ---
        # Stored in UTC. The Rollback Worker reads this table in descending
        # timestamp order to undo steps in reverse chronological order.
        sa.Column(
            "timestamp",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),

        # --- Context ---
        # JSONB stores structured metadata about this specific transition —
        # e.g. the EC2 instance ID that was launched, an error message from
        # a failed AWS API call, or the approval gate decision notes.
        # JSONB (binary JSON) is stored in a decomposed format that PostgreSQL
        # can index and query — unlike plain JSON which is stored as raw text.
        sa.Column("metadata", JSONB, nullable=True),

        # --- Constraints ---
        sa.PrimaryKeyConstraint("transition_id"),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.server_id"],
            name="fk_history_server_id",
            # ON DELETE RESTRICT: prevent deleting a server from the servers
            # table if it still has transition history. History is permanent —
            # you archive servers, you do not delete them.
            ondelete="RESTRICT",
        ),
    )

    # The single most important index in the system.
    # Every query the Rollback Worker makes is:
    # "give me all transitions for server X in reverse order"
    # Without this index that is a full table scan that gets slower
    # as the history table grows over thousands of migrations.
    op.create_index(
        "ix_history_server_id",
        "state_transition_history",
        ["server_id"],
    )

    # Index on timestamp — used for operational queries like
    # "show me everything that happened in the last hour" and for
    # the Rollback Worker's ORDER BY timestamp DESC queries.
    op.create_index(
        "ix_history_timestamp",
        "state_transition_history",
        ["timestamp"],
    )


def downgrade() -> None:
    op.drop_index("ix_history_timestamp", table_name="state_transition_history")
    op.drop_index("ix_history_server_id", table_name="state_transition_history")
    op.drop_table("state_transition_history")
